<?php
session_start();
header('Content-type:text/html;charset=utf-8');
date_default_timezone_set('PRC');
//数据库配置
define('DB_HOST','127.0.0.1');
define('DB_PORT',3306);
define('DB_USER','root');
define('DB_PWD','root');
define('DB_CHARSET','utf8');
define('DB_NAME','shop');
//系统常量
define("ROOT",str_replace("\\","/",dirname(__FILE__)));
define("PUBLIC_DIR",ROOT.'/public');
define("UPLOAD_DIR",ROOT.'/public/upload');
define("UPLOAD",'http://'.$_SERVER['HTTP_HOST'].'/demo/projects'.'/public/upload');
define("SKIN",'http://'.$_SERVER['HTTP_HOST'].'/demo/projects'.'/home/skin/default');
define("SKIN_ADMIN",'http://'.$_SERVER['HTTP_HOST'].'/admin/skin/default');
define("HTTP",'http://'.$_SERVER['HTTP_HOST'].'/demo/projects'.'/admin/skin/default');
set_include_path(get_include_path().PATH_SEPARATOR.PUBLIC_DIR.PATH_SEPARATOR.PUBLIC_DIR.'/lib');

include_once"common.inc.php";
include_once"image.inc.php";
include_once"mysql.inc.php";
